"""create_complaints_table

Revision ID: d47dcf169166
Revises: 
Create Date: 2026-09-16 14:49:11.180176
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'd47dcf169166'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_source', sa.String(length=255), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_strength_grade', sa.String(length=255), nullable=True),
    sa.Column('batch_lot_number', sa.String(length=255), nullable=True),
    sa.Column('affected_quantity', sa.String(length=255), nullable=True),
    sa.Column('manufacturing_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('complaint_type', sa.String(length=255), nullable=False),
    sa.Column('complaint_date', sa.Date(), nullable=False),
    sa.Column('detailed_complaint_description', sa.Text(), nullable=False),
    sa.Column('initial_severity', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=100), nullable=True),
    sa.Column('recommended_next_action', sa.Text(), nullable=True),
    sa.Column('ledger_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaints')
    # ### end Alembic commands ###
